# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
        - id: format_meson_build_files
          name: format_meson_build_files
          entry: ./scripts/format_meson_build_files.sh
          language: script
          pass_filenames: false
-   repo: local
    hooks:
        - id: format_cpp
          name: format_cpp
          entry: ./scripts/format_cpp.sh
          language: script
          pass_filenames: false
